name: imbutter
description: Imba in Flutter

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.3.2
  shelf: ^1.3.0
  shelf_router: ^1.1.2
  url_launcher: ^6.0.20
  just_audio: ^0.9.24

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/index.html
    - assets/js/
    - assets/css/
    - assets/audio/
